name: Customer Service CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@4

      - name: Print Message
        run: |
          echo "Welcome to GA"
          echo "Pipeline Started Successfully"
